CREATE TABLE gts_countries
(
	gts_country_id INT NOT NULL PRIMARY KEY UNIQUE AUTO_INCREMENT,
    gts_country_name varchar(255),
    gts_country_description varchar(255),
    gts_country_status boolean
);

INSERT INTO gts_countries
 (gts_country_id , gts_country_name , gts_country_description , gts_country_status )
VALUES (91 , 'India' , 'India description' , 1),
 (86 , 'China' , 'China description' , 1),
  (1 , 'United States' , 'United States description' , 1),
  (62 , 'Indonesia' , 'Indonesia description' , 1),
 (92 , 'Pakistan' , 'Pakistan description' , 1),
 (55 , 'Brazil' , 'Brazil description' , 1),
 (234 , 'Nigeria' , 'Nigeria description' , 1),
 (880 , 'Bangladesh' , 'Bangladesh description' , 1),
(7 , 'Russia' , 'Russia description' , 1),
  (52 , 'Mexico' , 'Mexico description' , 1),
(81 , 'Japan' , 'Japan description' , 1),
 (251 , 'Ethiopia Empire' , 'Ethiopia Empire description' , 1),
 (63 , 'Philippines' , 'Philippines description' , 1),
 (20 , 'Egypt' , 'Egypt description' , 1),
 (84 , 'Vietnam' , 'Vietnam description' , 1),
(243 , 'DR Congo' , 'DR Congo description' , 1),
 (90 , 'Turkey' , 'Turkey description' , 1),
 (98 , 'Iran' , 'Iran description' , 1),
 (49 , 'Germany' , 'Germany description' , 1),
 (66 , 'Thailand' , 'Thailand description' , 1),
 (44 , 'United Kingdom' , 'United Kingdom description' , 1),
 (33 , 'France' , 'France description' , 1),
 (39 , 'Italy' , 'Italy description' , 1),
 (255 , 'Tanzania' , 'Tanzania description' , 1),
 (27 , 'South Africa' , 'South Africa description' , 1),
 (95 , 'Myanmar' , 'Myanmar description' , 1),
 (254 , 'Kenya' , 'Kenya description' , 1),
 (82 , 'South Korea' , 'South Korea description' , 1),
 (57 , 'Colombia' , 'Colombia description' , 1),
 (34 , 'Spain' , 'Spain description' , 1),
 (256 , 'Uganda' , 'Uganda description' , 1),
 (54 , 'Argentina' , 'Argentina description' , 1),
 (213 , 'Algeria' , 'Algeria description' , 1),
 (249 , 'Sudan' , 'Sudan description' , 1),
 (380 , 'Ukraine' , 'Ukraine description' , 1),
 (964 , 'Iraq' , 'Iraq description' , 1),
 (93 , 'Afghanistan' , 'Afghanistan description' , 1),
 (48 , 'Poland' , 'Poland description' , 1),
 
 (212 , 'Morocco' , 'Morocco description' , 1),
 (966 , 'Saudi Arabia' , 'Saudi Arabia description' , 1),
 (998 , 'Uzbekistan' , 'Uzbekistan description' , 1),
 (51 , 'Peru' , 'Peru description' , 1),
 (244 , 'Angola' , 'Angola description' , 1),
 (60 , 'Malaysia' , 'Malaysia description' , 1),
(258 , 'Mozambique' , 'Mozambique description' , 1),
 (233 , 'Ghana' , 'Ghana description' , 1),
  (967 , 'Yemen' , 'Yemen description' , 1),
  (977 , 'Nepal' , 'Nepal description' , 1),
 ( 58, 'Venezuela' , 'Venezuela description' , 1),
  (261 , 'Madagascar' , 'Madagascar description' , 1),
  (237 , 'Cameroon' , 'Cameroon description' , 1), 
(225 , 'Côte d Ivoire' , 'Côte d Ivoire description' , 1),
(850 , 'North Korea' , 'North Korea description' , 1),
  (61 , 'Australia' , 'Australia description' , 1),
(227 , 'Niger' , 'Niger description' , 1),
 (94 , 'Sri Lanka' , 'Sri Lanka description' , 1),
 (226 , 'Burkina Faso' , 'Burkina Faso description' , 1),
 (223 , 'Mali' , 'Mali description' , 1),
 (40 , 'Romania' , 'Romania description' , 1),
(265 , 'Malawi' , 'Malawi description' , 1),
 (56 , 'Chile' , 'Chile description' , 1),
 (260 , 'Zambia' , 'Zambia description' , 1),
 (502 , 'Guatemala' , 'Guatemala description' , 1),
 (593 , 'Ecuador' , 'Ecuador description' , 1),
 (963 , 'Syria' , 'Syria description' , 1),
 (31 , 'Netherlands' , 'Netherlands description' , 1),
 (221 , 'Senegal' , 'Senegal description' , 1),
 (855 , 'Cambodia' , 'Cambodia description' , 1),
 (235 , 'Chad' , 'Chad description' , 1),
 (252 , 'Somalia' , 'Somalia description' , 1),
 (263 , 'Zimbabwe' , 'Zimbabwe description' , 1),
 (224 , 'Guinea' , 'Guinea description' , 1),
 (250 , 'Rwanda' , 'Rwanda description' , 1),
 (229 , 'Benin' , 'Benin description' , 1),
 (257 , 'Burundi' , 'Burundi description' , 1),
 (216 , 'Tunisia' , 'Tunisia description' , 1),
 (591 , 'Bolivia' , 'Bolivia description' , 1),
 (32 , 'Belgium' , 'Belgium description' , 1),
 (509 , 'Haiti' , 'Haiti description' , 1),
 (53 , 'Cuba' , 'Cuba description' , 1),
 (211 , 'South Sudan' , 'South Sudan description' , 1),
 (420 , 'Czech Republic' , 'Czech Republic description' , 1),
 (30 , 'Greece' , 'Greece description' , 1),
 (962 , 'Jordan' , 'Jordan description' , 1),
 (351 , 'Portugal' , 'Portugal description' , 1),
 (994 , 'Azerbaijan' , 'Azerbaijan description' , 1),
 (46 , 'Sweden' , 'Sweden description' , 1),
 (504 , 'Honduras' , 'Honduras description' , 1),
(971 , 'United Arab Emirates' , 'United Arab Emirates description' , 1),
 (36 , 'Hungary' , 'Hungary description' , 1),
  (992 , 'Tajikistan' , 'Tajikistan description' , 1),
  (375 , 'Belarus' , 'Belarus description' , 1),
 (43 , 'Austria' , 'Austria description' , 1),
 (675 , 'Papua New Guinea' , 'Papua New Guinea description' , 1),
 (381 , 'Serbia' , 'Serbia description' , 1),
 (972 , 'Israel' , 'Israel description' , 1),
(41 , 'Switzerland' , 'Switzerland description' , 1),
  (228 , 'Togo' , 'Togo description' , 1),
(232 , 'Sierra Leone' , 'Sierra Leone description' , 1),
 (856 , 'Laos' , 'Laos description' , 1),
 (595 , 'Paraguay' , 'Paraguay description' , 1),
 (359 , 'Bulgaria' , 'Bulgaria description' , 1),
 (218 , 'Libya' , 'Libya description' , 1),
(961 , 'Lebanon' , 'Lebanon description' , 1),
 (505 , 'Nicaragua' , 'Nicaragua description' , 1),
 (996, 'Kyrgyzstan' , 'Kyrgyzstan description' , 1),
 (503 , 'El Salvador' , 'El Salvador description' , 1),
 (993 , 'Turkmenistan' , 'Turkmenistan description' , 1),
 (65 , 'Singapore' , 'Singapore description' , 1),
 (45 , 'Denmark' , 'Denmark description' , 1),
 (358 , 'Finland' , 'Finland description' , 1),
 (242 , 'Congo' , 'Congo description' , 1),
 (421 , 'Slovakia' , 'Slovakia description' , 1),
 (47 , 'Norway' , 'Norway description' , 1),
 (968 , 'Oman' , 'Oman description' , 1),
 (970 , 'State of Palestine' , 'State of Palestine description' , 1),
 (506 , 'Costa Rica' , 'Costa Rica description' , 1),
 (231 , 'Liberia' , 'Liberia description' , 1),
 (353 , 'Ireland' , 'Ireland description' , 1),
 (236 , 'Central African Republic' , 'Central African Republic description' , 1),
 (64 , 'New Zealand' , 'New Zealand description' , 1),
 (222 , 'Mauritania' , 'Mauritania description' , 1),
 (507 , 'Panama' , 'Panama description' , 1),
 (965 , 'Kuwait' , 'Kuwait description' , 1),
 (385 , 'Croatia' , 'Croatia description' , 1),
 (373 , 'Moldova' , 'Moldova description' , 1),
 (995 , 'Georgia' , 'Georgia description' , 1),
 (291 , 'Eritrea' , 'Eritrea description' , 1),
 (598 , 'Uruguay' , 'Uruguay description' , 1),
 (387 , 'Bosnia and Herzegovina' , 'Bosnia and Herzegovina description' , 1),
 (976 , 'Mongolia' , 'Mongolia description' , 1),
 (374 , 'Armenia' , 'Armenia description' , 1),
 (974 , 'Qatar' , 'Qatar description' , 1),
(355 , 'Albania' , 'Albania description' , 1),
 (370 , 'Lithuania' , 'Lithuania description' , 1),
  (264 , 'Namibia' , 'Namibia description' , 1),
  (220 , 'Gambia' , 'Gambia description' , 1),
 (267 , 'Botswana' , 'Botswana description' , 1),
 (241 , 'Gabon' , 'Gabon description' , 1),
 (266 , 'Lesotho' , 'Lesotho description' , 1),
 (389 , 'North Macedonia' , 'North Macedonia description' , 1),
(386 , 'Slovenia' , 'Slovenia description' , 1),
  (245 , 'Guinea-Bissau' , 'Guinea-Bissau description' , 1),
(371 , 'Latvia' , 'Latvia description' , 1),
 (973 , 'Bahrain' , 'Bahrain description' , 1),
 (240 , 'Equatorial Guinea' , 'Equatorial Guinea description' , 1),
 (372 , 'Estonia' , 'Estonia description' , 1),
(670 , 'Timor-Leste' , 'Timor-Leste description' , 1),
 (230 , 'Mauritius' , 'Mauritius description' , 1),
 (357 , 'Cyprus' , 'Cyprus description' , 1),
 (268 , 'Eswatini' , 'Eswatini description' , 1),
 (253 , 'Djibouti' , 'Djibouti description' , 1),
 (679 , 'Fiji' , 'Fiji description' , 1),
 (269 , 'Comoros' , 'Comoros description' , 1),
 (592 , 'Guyana' , 'Guyana description' , 1),
 (975 , 'Bhutan' , 'Bhutan description' , 1),
 (677 , 'Solomon Islands' , 'Solomon Islands description' , 1),
 (382 , 'Montenegro' , 'Montenegro description' , 1),
 (352 , 'Luxembourg' , 'Luxembourg description' , 1),
 (597 , 'Suriname' , 'Suriname description' , 1),
 (238 , 'Cabo Verde' , 'Cabo Verde description' , 1),
 (960 , 'Maldives' , 'Maldives description' , 1),
 (356 , 'Malta' , 'Malta description' , 1),
 (673 , 'Brunei' , 'Brunei description' , 1),
 (501 , 'Belize' , 'Belize description' , 1),
 (354 , 'Iceland' , 'Iceland description' , 1),
 (678 , 'Vanuatu' , 'Vanuatu description' , 1),
 (239 , 'Sao Tome and Principe' , 'Sao Tome and Principe description' , 1),
 (685 , 'Samoa' , 'Samoa description' , 1),
 (686 , 'Kiribati' , 'Kiribati description' , 1),
 (691 , 'Micronesia' , 'Micronesia description' , 1),
 (784 , 'St.Vincent and Grenadines' , 'St.Vincent and Grenadines description' , 1),
 (676 , 'Tonga' , 'Tonga description' , 1),
 (248 , 'Seychelles' , 'Seychelles description' , 1),
 (376 , 'Andorra' , 'Andorra description' , 1),
 (692 , 'Marshall Islands' , '	Marshall Islands description' , 1),
 (377 , 'Monaco' , 'Monaco description' , 1),
 (423 , 'Liechtenstein' , 'Liechtenstein description' , 1),
 (378 , 'San Marino' , 'San Marino description' , 1),
 (680 , 'Palau' , 'Palau description' , 1),
 (688 , 'Tuvalu' , 'Tuvalu description' , 1),
 (674 , 'Nauru' , 'Nauru description' , 1),
 (379 , 'Holy See' , 'Holy See description' , 1);

SELECT * FROM gts_chakuri_db.gts_countries;






 