CREATE TABLE gts_countries
(
    gts_country_id INT NOT NULL PRIMARY KEY UNIQUE ,
    gts_country_name varchar(255) UNIQUE,
    gts_country_description varchar(255),
    gts_country_status boolean
);

INSERT INTO gts_countries
(gts_country_id , gts_country_name , gts_country_description , gts_country_status )
 VALUES (1 , 'United States' , 'United States' , 1),
 (7 , 'Russia' , 'Russia' , 1),
 (20 , 'Egypt' , 'Egypt' , 1),
 (27 , 'South Africa' , 'South Africa' , 1),
 (30 , 'Greece' , 'Greece' , 1),
 (31 , 'Netherlands' , 'Netherlands' , 1),
 (32 , 'Belgium' , 'Belgium' , 1),
 (33 , 'France' , 'France' , 1),
 (34 , 'Spain' , 'Spain' , 1),
 (36 , 'Hungary' , 'Hungary' , 1),
 (39 , 'Italy' , 'Italy' , 1),
 (40 , 'Romania' , 'Romania' , 1),
 (41 , 'Switzerland' , 'Switzerland' , 1), 
 (43 , 'Austria' , 'Austria' , 1),
 (44 , 'United Kingdom' , 'United Kingdom' , 1),
 (45 , 'Denmark' , 'Denmark' , 1),
 (46 , 'Sweden' , 'Sweden description' , 1),
 (47 , 'Norway' , 'Norway' , 1),
 (48 , 'Poland' , 'Poland' , 1),
 (49 , 'Germany' , 'Germany' , 1),
 (51 , 'Peru' , 'Peru' , 1),
 (52 , 'Mexico' , 'Mexico' , 1),
 (53 , 'Cuba' , 'Cuba' , 1),
 (54 , 'Argentina' , 'Argentina' , 1),
 (55 , 'Brazil' , 'Brazil' , 1),
 (56 , 'Chile' , 'Chile' , 1),
 (57 , 'Colombia' , 'Colombia' , 1),
 (58, 'Venezuela' , 'Venezuela' , 1),
 (60 , 'Malaysia' , 'Malaysia' , 1),
 (61 , 'Australia' , 'Australia' , 1),
 (62 , 'Indonesia' , 'Indonesia' , 1),
 (63 , 'Philippines' , 'Philippines' , 1),
 (64 , 'New Zealand' , 'New Zealand' , 1),
 (65 , 'Singapore' , 'Singapore' , 1),
 (66 , 'Thailand' , 'Thailand' , 1),
 (81 , 'Japan' , 'Japan' , 1),
 (82 , 'South Korea' , 'South Korea' , 1),
 (84 , 'Vietnam' , 'Vietnam' , 1),
 (86 , 'China' , 'China' , 1),
 (90 , 'Turkey' , 'Turkey' , 1),
 (91 , 'India' , 'India' , 1),
 (92 , 'Pakistan' , 'Pakistan' , 1),
 (93 , 'Afghanistan' , 'Afghanistan' , 1),
 (94 , 'Sri Lanka' , 'Sri Lanka' , 1),
 (95 , 'Myanmar' , 'Myanmar' , 1),
 (98 , 'Iran' , 'Iran' , 1),
 (211 , 'South Sudan' , 'South Sudan' , 1),
 (212 , 'Morocco' , 'Morocco' , 1),
 (213 , 'Algeria' , 'Algeria' , 1),
 (216 , 'Tunisia' , 'Tunisia' , 1),
 (218 , 'Libya' , 'Libya' , 1),
 (220 , 'Gambia' , 'Gambia' , 1),
 (221 , 'Senegal' , 'Senegal' , 1),
 (222 , 'Mauritania' , 'Mauritania' , 1),
 (223 , 'Mali' , 'Mali' , 1),
 (224 , 'Guinea' , 'Guinea' , 1),
 (225 , 'Côte d Ivoire' , 'Côte d Ivoire' , 1),
 (226 , 'Burkina Faso' , 'Burkina Faso' , 1),
 (227 , 'Niger' , 'Niger' , 1),
 (228 , 'Togo' , 'Togo' , 1),
 (229 , 'Benin' , 'Benin' , 1),
 (230 , 'Mauritius' , 'Mauritius' , 1),
 (231 , 'Liberia' , 'Liberia' , 1),
 (232 , 'Sierra Leone' , 'Sierra Leone' , 1),
 (233 , 'Ghana' , 'Ghana' , 1),
 (234 , 'Nigeria' , 'Nigeria' , 1),
 (235 , 'Chad' , 'Chad' , 1),
 (236 , 'Central African Republic' , 'Central African Republic' , 1),
 (237 , 'Cameroon' , 'Cameroon' , 1),
 (238 , 'Cabo Verde' , 'Cabo Verde' , 1),
 (239 , 'Sao Tome and Principe' , 'Sao Tome and Principe' , 1),
 (240 , 'Equatorial Guinea' , 'Equatorial Guinea' , 1), 
 (241 , 'Gabon' , 'Gabon' , 1),
 (242 , 'Congo' , 'Congo' , 1),
 (243 , 'DR Congo' , 'DR Congo' , 1),
 (244 , 'Angola' , 'Angola' , 1),
 (245 , 'Guinea-Bissau' , 'Guinea-Bissau' , 1),
 (248 , 'Seychelles' , 'Seychelles' , 1),
 (249 , 'Sudan' , 'Sudan' , 1),
 (250 , 'Rwanda' , 'Rwanda' , 1),
 (251 , 'Ethiopia Empire' , 'Ethiopia Empire' , 1),
 (252 , 'Somalia' , 'Somalia' , 1),
 (253 , 'Djibouti' , 'Djibouti' , 1),
 (254 , 'Kenya' , 'Kenya' , 1),
 (256 , 'Uganda' , 'Uganda' , 1),
 (257 , 'Burundi' , 'Burundi' , 1),
 (258 , 'Mozambique' , 'Mozambique' , 1),
 (260 , 'Zambia' , 'Zambia' , 1),
 (261 , 'Madagascar' , 'Madagascar' , 1),
 (263 , 'Zimbabwe' , 'Zimbabwe' , 1),
 (264 , 'Namibia' , 'Namibia' , 1),
 (265 , 'Malawi' , 'Malawi' , 1),
 (266 , 'Lesotho' , 'Lesotho' , 1),
 (267 , 'Botswana' , 'Botswana' , 1),
 (268 , 'Eswatini' , 'Eswatini' , 1),
 (269 , 'Comoros' , 'Comoros' , 1),
 (291 , 'Eritrea' , 'Eritrea' , 1),
 (351 , 'Portugal' , 'Portugal' , 1),
 (352 , 'Luxembourg' , 'Luxembourg' , 1),
 (353 , 'Ireland' , 'Ireland' , 1),
 (354 , 'Iceland' , 'Iceland' , 1),
 (355 , 'Albania' , 'Albania' , 1),
 (356 , 'Malta' , 'Malta' , 1),
 (357 , 'Cyprus' , 'Cyprus' , 1),
 (358 , 'Finland' , 'Finland' , 1),
 (359 , 'Bulgaria' , 'Bulgaria' , 1),
 (370 , 'Lithuania' , 'Lithuania' , 1),
 (371 , 'Latvia' , 'Latvia' , 1),
 (372 , 'Estonia' , 'Estonia' , 1),
 (373 , 'Moldova' , 'Moldova' , 1),
 (374 , 'Armenia' , 'Armenia' , 1), 
 (375 , 'Belarus' , 'Belarus' , 1),
 (376 , 'Andorra' , 'Andorra' , 1),
 (377 , 'Monaco' , 'Monaco' , 1),
 (378 , 'San Marino' , 'San Marino' , 1),
 (379 , 'Holy See' , 'Holy See' , 1),
 (380 , 'Ukraine' , 'Ukraine' , 1),
 (381 , 'Serbia' , 'Serbia' , 1),
 (382 , 'Montenegro' , 'Montenegro' , 1),
 (385 , 'Croatia' , 'Croatia' , 1),
 (386 , 'Slovenia' , 'Slovenia' , 1),
 (387 , 'Bosnia and Herzegovina' , 'Bosnia and Herzegovina' , 1),
 (389 , 'North Macedonia' , 'North Macedonia' , 1),
 (420 , 'Czech Republic' , 'Czech Republic' , 1),
 (421 , 'Slovakia' , 'Slovakia' , 1),
 (423 , 'Liechtenstein' , 'Liechtenstein' , 1),
 (501 , 'Belize' , 'Belize' , 1),
 (502 , 'Guatemala' , 'Guatemala' , 1), 
 (503 , 'El Salvador' , 'El Salvador' , 1),
 (504 , 'Honduras' , 'Honduras' , 1),
 (505 , 'Nicaragua' , 'Nicaragua' , 1),
 (506 , 'Costa Rica' , 'Costa Rica' , 1),
 (507 , 'Panama' , 'Panama' , 1),
 (509 , 'Haiti' , 'Haiti' , 1),
 (591 , 'Bolivia' , 'Bolivia' , 1),
 (592 , 'Guyana' , 'Guyana' , 1),
 (593 , 'Ecuador' , 'Ecuador' , 1),
 (595 , 'Paraguay' , 'Paraguay' , 1),
 (597 , 'Suriname' , 'Suriname' , 1),
 (598 , 'Uruguay' , 'Uruguay' , 1),
 (670 , 'Timor-Leste' , 'Timor-Leste' , 1),
 (673 , 'Brunei' , 'Brunei' , 1),
 (674 , 'Nauru' , 'Nauru' , 1),
 (675 , 'Papua New Guinea' , 'Papua New Guinea' , 1),
 (676 , 'Tonga' , 'Tonga' , 1),
 (677 , 'Solomon Islands' , 'Solomon Islands' , 1),
 (678 , 'Vanuatu' , 'Vanuatu' , 1),
 (679 , 'Fiji' , 'Fiji' , 1),
 (680 , 'Palau' , 'Palau' , 1),
 (685 , 'Samoa' , 'Samoa' , 1),
 (686 , 'Kiribati' , 'Kiribati' , 1),
 (688 , 'Tuvalu' , 'Tuvalu' , 1),
 (691 , 'Micronesia' , 'Micronesia' , 1),
 (692 , 'Marshall Islands' , '	Marshall Islands' , 1),
 (784 , 'St.Vincent and Grenadines' , 'St.Vincent and Grenadines' , 1),
 (850 , 'North Korea' , 'North Korea' , 1),
 (855 , 'Cambodia' , 'Cambodia' , 1),
 (856 , 'Laos' , 'Laos' , 1),
 (880 , 'Bangladesh' , 'Bangladesh' , 1),
 (960 , 'Maldives' , 'Maldives' , 1),
 (961 , 'Lebanon' , 'Lebanon' , 1),
 (962 , 'Jordan' , 'Jordan' , 1),
 (963 , 'Syria' , 'Syria' , 1),
 (964 , 'Iraq' , 'Iraq' , 1),
 (965 , 'Kuwait' , 'Kuwait' , 1),
 (966 , 'Saudi Arabia' , 'Saudi Arabia' , 1),
 (967 , 'Yemen' , 'Yemen' , 1),
 (968 , 'Oman' , 'Oman' , 1),
 (970 , 'State of Palestine' , 'State of Palestine' , 1),
 (971 , 'United Arab Emirates' , 'United Arab Emirates' , 1),
 (972 , 'Israel' , 'Israel' , 1),
 (973 , 'Bahrain' , 'Bahrain' , 1),
 (974 , 'Qatar' , 'Qatar' , 1),
 (975 , 'Bhutan' , 'Bhutan' , 1),
 (976 , 'Mongolia' , 'Mongolia' , 1),
 (977 , 'Nepal' , 'Nepal' , 1),
 (992 , 'Tajikistan' , 'Tajikistan' , 1),
 (993 , 'Turkmenistan' , 'Turkmenistan' , 1),
 (994 , 'Azerbaijan' , 'Azerbaijan' , 1),
 (995 , 'Georgia' , 'Georgia' , 1),
 (996, 'Kyrgyzstan' , 'Kyrgyzstan' , 1),
 (998 , 'Uzbekistan' , 'Uzbekistan' , 1);
 



SELECT * FROM gts_chakuri_db.gts_countries;






 
